#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE      24000
#define AUDIO_OUTPUT_SAMPLE_RATE     24000

#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_3
#define AUDIO_I2S_GPIO_WS GPIO_NUM_9
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_46
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_14
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_10

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_41
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_42
#define AUDIO_CODEC_ES8388_ADDR ES8388_CODEC_DEFAULT_ADDR

#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  0x82

#define BOOT_BUTTON_GPIO GPIO_NUM_18

#define BUILTIN_LED_GPIO GPIO_NUM_1

// ST7735 0.9寸 128x128 圆形屏
// 诊断结论：白→黑、黑→白 表示面板存在反相特性，需要 DISPLAY_INVERT_COLOR=true 让驱动发 INVON 切换。
// 注：虽然 esp32-cgc 的 ST7735_128X128 用 false，但本面板的 OTP 默认状态不同，需要 true。
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_BGR

// ST7735 128x128 圆屏偏移量（与 esp32-cgc 一致）
// #define DISPLAY_OFFSET_X  2
// #define DISPLAY_OFFSET_Y 3

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_48
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define DISPLAY_SCLK_PIN    GPIO_NUM_12
#define DISPLAY_MOSI_PIN    GPIO_NUM_11
#define DISPLAY_CS_PIN      GPIO_NUM_21
#define DISPLAY_DC_PIN      GPIO_NUM_13
#define DISPLAY_RESET_PIN   GPIO_NUM_47

// SPI 时钟 20MHz（与 esp32-cgc 一致）
#define DISPLAY_SPI_SCLK_HZ     (20 * 1000 * 1000)
#define DISPLAY_SPI_MODE        0

// 兼容旧宏
#define DISPLAY_SPI_SCLK_PIN    DISPLAY_SCLK_PIN
#define DISPLAY_SPI_MOSI_PIN    DISPLAY_MOSI_PIN
#define DISPLAY_SPI_CS_PIN      DISPLAY_CS_PIN
#define DISPLAY_SPI_DC_PIN      DISPLAY_DC_PIN
#define DISPLAY_SPI_RESET_PIN   DISPLAY_RESET_PIN

#endif // _BOARD_CONFIG_H_
